services:
  rabbitmq_x:
      image: rabbitmq:3.12-management
      container_name: rabbitmq_x
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"

  write_api_x:
    build: .
    container_name: write_api_x
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres_x
      - rabbitmq_x
      - mongodb_x
    env_file:
      - .env

  worker_x:
    build: .
    container_name: rabbitmq_worker_x
    command: python -m app.workers.rabbitmq_worker
    depends_on:
      - rabbitmq_x
      - mongodb_x
    env_file:
      - .env

  read_api_x:
    build: .
    container_name: read_api_x
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - mongodb_x
    env_file:
      - .env

  postgres_x:
    image: postgres:16
    container_name: postgres_db_x
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb_x:
    image: mongo:4.4
    container_name: mongodb_x
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: