apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: event-platform

data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: events_db

  MONGO_HOST: mongodb-service
  MONGO_PORT: "27017"

  RABBITMQ_HOST: rabbitmq-service
  RABBITMQ_PORT: "5672"