apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: event-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      nodeSelector:
        node-type: worker
      containers:
        - name: worker
          image: vinaydavda7/event_system_x:latest
          command: ["python"]
          args: ["-m", "app.workers.rabbitmq_worker"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret